### ISSUE TITLE
Extend KillrVideo into graph - 360

### ISSUE THREAD

**Issue by SonicDMG** [KillrVideo/killrvideo.github.io#16]
We don't currently showcase any graph capabilities with KillrVideo.  

Hook up the API for real-time updates
Create some meaningful 360 like model to demonstrate capabilities outside of base analytics

**Comment by SonicDMG** [comment]
I currently have a whole set of graph queries and started into creating a set of "questions" for KillrVideo that only graph could answer, but I'm not really that far into it.  I also have an external, mixed-workload search/graph cluster in place with a DSE graphloader script in place and working along with a base schema.

**Comment by jeffreyscarpenter** [comment]
Closing - replaced by projects/tasks under top-level organization.
