### ISSUE TITLE
Provide combined search/analytics/graph capability for KillrVideo

### ISSUE THREAD

**Issue by SonicDMG** [KillrVideo/killrvideo.github.io#18]
This is tied to both
https://github.com/KillrVideo/killrvideo.github.io/issues/16
and
https://github.com/KillrVideo/killrvideo.github.io/issues/17

The goal here is to combine the power of search, graph, and analytics and provide references that devs can use to implement all 3

**Comment by jeffreyscarpenter** [comment]
Closing - replaced by projects/tasks under top-level organization.
