### ISSUE TITLE
Make sure automatic CI deploys still work

### ISSUE THREAD

**Issue by LukeTillman** [KillrVideo/killrvideo.github.io#24]
Travis just made a change to read-only keys when cloning from GitHub. You can find details here:

https://blog.travis-ci.com/2017-11-01-security-advisory-ro-deploy-keys

I don't *think* this will impact us here because it looks like we're using a separate encrypted deploy key for pushing to Git, but you probably want to double-check. And if things *do* start breaking, I wanted to give you heads-up on one possible cause.

**Comment by SonicDMG** [comment]
I assigned this to Jeff because he happens to be working on the bootstrap right now and is most likely deploying a lot.

**Comment by LukeTillman** [comment]
Just to be clear, I put this under the docs site repository because I think only this repository could be affected (since it's the only one I can think of right now that does a `git push` to GitHub in order to publish). The other repos that push Docker images shouldn't be impacted.

**Comment by jeffreyscarpenter** [comment]
Closing this issue as automated publishing has not been affected.
